"""Warranty

Revision ID: 00a8b93a2712
Revises: 15079e25d540
Create Date: 2025-11-08 12:23:58.327231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '00a8b93a2712'
down_revision: Union[str, Sequence[str], None] = '15079e25d540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warranty', sa.Column('invoice_number', sa.VARCHAR(length=16), nullable=True))
    op.drop_column('warranty', 'invoice')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warranty', sa.Column('invoice', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.drop_column('warranty', 'invoice_number')
    # ### end Alembic commands ###
