"""Warranty

Revision ID: 15079e25d540
Revises: f7cb7a5b9050
Create Date: 2025-11-08 12:21:50.262823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '15079e25d540'
down_revision: Union[str, Sequence[str], None] = 'f7cb7a5b9050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warranty',
    sa.Column('srf_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=5), nullable=False),
    sa.Column('srf_date', sa.DATE(), nullable=False),
    sa.Column('head', sa.VARCHAR(length=15), nullable=False),
    sa.Column('division', sa.VARCHAR(length=15), nullable=False),
    sa.Column('model', sa.VARCHAR(length=30), nullable=False),
    sa.Column('serial_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('problem', sa.VARCHAR(length=30), nullable=False),
    sa.Column('remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('complaint_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('sticker_number', sa.VARCHAR(length=15), nullable=True),
    sa.Column('asc_name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('challan_number', sa.VARCHAR(length=6), nullable=True),
    sa.Column('challan_date', sa.DATE(), nullable=True),
    sa.Column('challan', sa.CHAR(length=1), nullable=False),
    sa.Column('courier', sa.VARCHAR(length=15), nullable=True),
    sa.Column('receive_date', sa.DATE(), nullable=True),
    sa.Column('invoice', sa.VARCHAR(length=16), nullable=True),
    sa.Column('invoice_date', sa.DATE(), nullable=True),
    sa.Column('repair_date', sa.DATE(), nullable=True),
    sa.Column('delivery_date', sa.DATE(), nullable=True),
    sa.Column('delivered_by', sa.VARCHAR(length=20), nullable=True),
    sa.Column('status', sa.VARCHAR(length=40), nullable=True),
    sa.Column('settlement', sa.CHAR(length=1), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=15), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=15), nullable=True),
    sa.ForeignKeyConstraint(['asc_name'], ['service_centre.asc_name'], ),
    sa.ForeignKeyConstraint(['code'], ['master.code'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('srf_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warranty')
    # ### end Alembic commands ###
