"""Initial Migration

Revision ID: 16ef08de4db0
Revises: 
Create Date: 2025-11-08 11:21:18.598575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '16ef08de4db0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.VARCHAR(), server_default='USER', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('master',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), nullable=False),
    sa.Column('address', sa.VARCHAR(length=40), nullable=False),
    sa.Column('city', sa.VARCHAR(length=20), nullable=False),
    sa.Column('pin', sa.VARCHAR(length=6), nullable=True),
    sa.Column('contact1', sa.VARCHAR(length=10), nullable=True),
    sa.Column('contact2', sa.VARCHAR(length=10), nullable=True),
    sa.Column('gst', sa.VARCHAR(length=15), nullable=True),
    sa.Column('remark', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=20), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('master')
    op.drop_table('users')
    # ### end Alembic commands ###
