"""ASC Name

Revision ID: 1d2474508945
Revises: 77d8e9cf94a0
Create Date: 2025-11-30 23:42:18.863216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1d2474508945'
down_revision: Union[str, Sequence[str], None] = '77d8e9cf94a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('warranty_asc_name_fkey'), 'warranty', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('warranty_asc_name_fkey'), 'warranty', 'service_centre', ['asc_name'], ['asc_name'])
    # ### end Alembic commands ###
