"""Commit

Revision ID: 1ece8179ff5e
Revises: b8e03a26a3fd
Create Date: 2025-11-18 09:22:49.112020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1ece8179ff5e'
down_revision: Union[str, Sequence[str], None] = 'b8e03a26a3fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)
    # ### end Alembic commands ###
