"""JTI

Revision ID: 36bfb740bff4
Revises: 4d40f911f536
Create Date: 2025-11-14 22:31:31.844631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '36bfb740bff4'
down_revision: Union[str, Sequence[str], None] = '4d40f911f536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockedjti',
    sa.Column('jti', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_index(op.f('ix_blockedjti_jti'), 'blockedjti', ['jti'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blockedjti_jti'), table_name='blockedjti')
    op.drop_table('blockedjti')
    # ### end Alembic commands ###
