"""Out_of_Warranty

Revision ID: 3d7580e8f38c
Revises: 00a8b93a2712
Create Date: 2025-11-08 12:47:20.194618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3d7580e8f38c'
down_revision: Union[str, Sequence[str], None] = '00a8b93a2712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('out_of_warranty',
    sa.Column('srf_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('srf_date', sa.DATE(), nullable=False),
    sa.Column('wcode', sa.VARCHAR(length=5), nullable=False),
    sa.Column('division', sa.VARCHAR(length=15), nullable=False),
    sa.Column('head', sa.VARCHAR(length=20), nullable=True),
    sa.Column('service_charge', sa.INTEGER(), nullable=False),
    sa.Column('model', sa.VARCHAR(length=30), nullable=False),
    sa.Column('serial_number', sa.VARCHAR(length=15), nullable=False),
    sa.Column('problem', sa.VARCHAR(length=30), nullable=True),
    sa.Column('remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('challan_number', sa.VARCHAR(length=6), nullable=True),
    sa.Column('challan_date', sa.DATE(), nullable=True),
    sa.Column('challan', sa.CHAR(length=1), nullable=False),
    sa.Column('received_by', sa.VARCHAR(length=20), nullable=True),
    sa.Column('estimate_date', sa.DATE(), nullable=True),
    sa.Column('vendor_date1', sa.DATE(), nullable=True),
    sa.Column('vendor_date2', sa.DATE(), nullable=True),
    sa.Column('vendor_cost1', sa.FLOAT(), nullable=True),
    sa.Column('vendor_cost2', sa.FLOAT(), nullable=True),
    sa.Column('repair_date', sa.DATE(), nullable=True),
    sa.Column('work_done', sa.VARCHAR(length=50), nullable=True),
    sa.Column('rewinding_cost', sa.FLOAT(), nullable=True),
    sa.Column('other_cost', sa.FLOAT(), nullable=True),
    sa.Column('spare1', sa.VARCHAR(length=20), nullable=True),
    sa.Column('cost1', sa.FLOAT(), nullable=True),
    sa.Column('spare2', sa.VARCHAR(length=20), nullable=True),
    sa.Column('cost2', sa.FLOAT(), nullable=True),
    sa.Column('spare3', sa.VARCHAR(length=20), nullable=True),
    sa.Column('cost3', sa.FLOAT(), nullable=True),
    sa.Column('spare4', sa.VARCHAR(length=20), nullable=True),
    sa.Column('cost4', sa.FLOAT(), nullable=True),
    sa.Column('spare5', sa.VARCHAR(length=20), nullable=True),
    sa.Column('cost5', sa.FLOAT(), nullable=True),
    sa.Column('spare6', sa.VARCHAR(length=20), nullable=True),
    sa.Column('cost6', sa.FLOAT(), nullable=True),
    sa.Column('spare_cost', sa.FLOAT(), nullable=True),
    sa.Column('godown_cost', sa.FLOAT(), nullable=True),
    sa.Column('discount', sa.FLOAT(), nullable=True),
    sa.Column('total', sa.FLOAT(), nullable=True),
    sa.Column('gst', sa.CHAR(length=1), nullable=False),
    sa.Column('gstamount', sa.FLOAT(), nullable=True),
    sa.Column('final_amount', sa.FLOAT(), nullable=True),
    sa.Column('round_off', sa.FLOAT(), nullable=True),
    sa.Column('receive_amount', sa.FLOAT(), nullable=True),
    sa.Column('delivery_date', sa.DATE(), nullable=True),
    sa.Column('pcno', sa.INTEGER(), nullable=True),
    sa.Column('invoice_number', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=1), nullable=False),
    sa.Column('vendor_bill_number', sa.VARCHAR(length=8), nullable=True),
    sa.Column('settlement_date', sa.DATE(), nullable=True),
    sa.Column('vendor_settlement_date', sa.DATE(), nullable=True),
    sa.Column('service_charge_waive', sa.CHAR(length=1), nullable=False),
    sa.Column('collection_date', sa.DATE(), nullable=True),
    sa.Column('waive_details', sa.VARCHAR(length=40), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=15), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=15), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.username'], ),
    sa.ForeignKeyConstraint(['wcode'], ['master.code'], ),
    sa.PrimaryKeyConstraint('srf_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('out_of_warranty')
    # ### end Alembic commands ###
