"""Indexing on customer

Revision ID: 40c7e2b9ac23
Revises: 2634639d402f
Create Date: 2025-11-12 20:44:20.893178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '40c7e2b9ac23'
down_revision: Union[str, Sequence[str], None] = '2634639d402f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_challan_challan_number'), 'challan', ['challan_number'], unique=False)
    op.create_index(op.f('ix_challan_code'), 'challan', ['code'], unique=False)
    op.create_index(op.f('ix_master_code'), 'master', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_code'), table_name='master')
    op.drop_index(op.f('ix_challan_code'), table_name='challan')
    op.drop_index(op.f('ix_challan_challan_number'), table_name='challan')
    # ### end Alembic commands ###
