"""Indexing on code

Revision ID: 4d40f911f536
Revises: 40c7e2b9ac23
Create Date: 2025-11-12 20:46:03.278223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4d40f911f536'
down_revision: Union[str, Sequence[str], None] = '40c7e2b9ac23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_market_code'), 'market', ['code'], unique=False)
    op.create_index(op.f('ix_market_mcode'), 'market', ['mcode'], unique=False)
    op.create_index(op.f('ix_out_of_warranty_code'), 'out_of_warranty', ['code'], unique=False)
    op.create_index(op.f('ix_out_of_warranty_srf_number'), 'out_of_warranty', ['srf_number'], unique=False)
    op.create_index(op.f('ix_retail_code'), 'retail', ['code'], unique=False)
    op.create_index(op.f('ix_retail_rcode'), 'retail', ['rcode'], unique=False)
    op.create_index(op.f('ix_warranty_code'), 'warranty', ['code'], unique=False)
    op.create_index(op.f('ix_warranty_srf_number'), 'warranty', ['srf_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warranty_srf_number'), table_name='warranty')
    op.drop_index(op.f('ix_warranty_code'), table_name='warranty')
    op.drop_index(op.f('ix_retail_rcode'), table_name='retail')
    op.drop_index(op.f('ix_retail_code'), table_name='retail')
    op.drop_index(op.f('ix_out_of_warranty_srf_number'), table_name='out_of_warranty')
    op.drop_index(op.f('ix_out_of_warranty_code'), table_name='out_of_warranty')
    op.drop_index(op.f('ix_market_mcode'), table_name='market')
    op.drop_index(op.f('ix_market_code'), table_name='market')
    # ### end Alembic commands ###
