"""Master Table

Revision ID: 5f18d347c280
Revises: 6feb92939142
Create Date: 2025-11-08 00:45:14.125816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5f18d347c280'
down_revision: Union[str, Sequence[str], None] = '6feb92939142'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), nullable=False),
    sa.Column('address', sa.VARCHAR(length=40), nullable=False),
    sa.Column('city', sa.VARCHAR(length=20), nullable=False),
    sa.Column('pin', sa.VARCHAR(length=6), nullable=True),
    sa.Column('contact1', sa.VARCHAR(length=10), nullable=True),
    sa.Column('contact2', sa.VARCHAR(length=10), nullable=True),
    sa.Column('gst', sa.VARCHAR(length=15), nullable=True),
    sa.Column('remark', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=20), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('master')
    # ### end Alembic commands ###
