"""Out of warranty

Revision ID: 658e7b12125e
Revises: 1d2474508945
Create Date: 2025-12-01 00:41:11.683621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '658e7b12125e'
down_revision: Union[str, Sequence[str], None] = '1d2474508945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('out_of_warranty', sa.Column('pc_number', sa.INTEGER(), nullable=True))
    op.add_column('out_of_warranty', sa.Column('final_status', sa.VARCHAR(length=1), nullable=False))
    op.add_column('out_of_warranty', sa.Column('vendor_final_status', sa.VARCHAR(length=1), nullable=False))
    op.drop_column('out_of_warranty', 'pcno')
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.add_column('out_of_warranty', sa.Column('pcno', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('out_of_warranty', 'vendor_final_status')
    op.drop_column('out_of_warranty', 'final_status')
    op.drop_column('out_of_warranty', 'pc_number')
    # ### end Alembic commands ###
