"""Retail

Revision ID: 6c682651ad62
Revises: 0c108d32becc
Create Date: 2025-12-11 09:13:19.748032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6c682651ad62'
down_revision: Union[str, Sequence[str], None] = '0c108d32becc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('retail', 'details',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('retail', 'details',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
    # ### end Alembic commands ###
