"""Retail

Revision ID: 77d8e9cf94a0
Revises: 9e4bc7b12b79
Create Date: 2025-11-28 20:20:21.194145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '77d8e9cf94a0'
down_revision: Union[str, Sequence[str], None] = '9e4bc7b12b79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challan', 'remark',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('market', 'final_status',
               existing_type=sa.CHAR(length=1),
               nullable=False)
    op.alter_column('retail', 'final_status',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.CHAR(length=1),
               nullable=False,
               existing_server_default=sa.text("'N'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('retail', 'final_status',
               existing_type=sa.CHAR(length=1),
               type_=sa.VARCHAR(length=1),
               nullable=True,
               existing_server_default=sa.text("'N'::character varying"))
    op.alter_column('market', 'final_status',
               existing_type=sa.CHAR(length=1),
               nullable=True)
    op.alter_column('challan', 'remark',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
