"""Out_of_Warranty

Revision ID: 8cfce09bfe9b
Revises: 3d7580e8f38c
Create Date: 2025-11-08 12:54:43.914209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8cfce09bfe9b'
down_revision: Union[str, Sequence[str], None] = '3d7580e8f38c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('out_of_warranty', sa.Column('code', sa.VARCHAR(length=5), nullable=False))
    op.add_column('out_of_warranty', sa.Column('gst_amount', sa.FLOAT(), nullable=True))
    op.drop_constraint(op.f('out_of_warranty_wcode_fkey'), 'out_of_warranty', type_='foreignkey')
    op.create_foreign_key(None, 'out_of_warranty', 'master', ['code'], ['code'])
    op.drop_column('out_of_warranty', 'wcode')
    op.drop_column('out_of_warranty', 'gstamount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('out_of_warranty', sa.Column('gstamount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('out_of_warranty', sa.Column('wcode', sa.VARCHAR(length=5), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'out_of_warranty', type_='foreignkey')
    op.create_foreign_key(op.f('out_of_warranty_wcode_fkey'), 'out_of_warranty', 'master', ['wcode'], ['code'])
    op.drop_column('out_of_warranty', 'gst_amount')
    op.drop_column('out_of_warranty', 'code')
    # ### end Alembic commands ###
