"""Foreign Key

Revision ID: 981c12f8e4f4
Revises: 5f18d347c280
Create Date: 2025-11-08 00:56:16.312845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '981c12f8e4f4'
down_revision: Union[str, Sequence[str], None] = '5f18d347c280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'master', 'users', ['created_by'], ['username'])
    op.create_foreign_key(None, 'master', 'users', ['updated_by'], ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'master', type_='foreignkey')
    op.drop_constraint(None, 'master', type_='foreignkey')
    # ### end Alembic commands ###
