"""JTI

Revision ID: b3d9221bfa47
Revises: bb2aafdf1445
Create Date: 2025-12-08 08:37:47.163300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3d9221bfa47'
down_revision: Union[str, Sequence[str], None] = 'bb2aafdf1445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blockedjti_jti'), table_name='blockedjti')
    op.drop_table('blockedjti')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockedjti',
    sa.Column('jti', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('jti', name=op.f('blockedjti_pkey'))
    )
    op.create_index(op.f('ix_blockedjti_jti'), 'blockedjti', ['jti'], unique=False)
    # ### end Alembic commands ###
