"""Initial migration

Revision ID: d59750ad56e8
Revises: 
Create Date: 2025-12-07 07:33:57.934087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd59750ad56e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockedjti',
    sa.Column('jti', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_index(op.f('ix_blockedjti_jti'), 'blockedjti', ['jti'], unique=False)
    op.create_table('service_centre',
    sa.Column('asc_name', sa.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('asc_name')
    )
    op.create_table('service_charge',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('division', sa.VARCHAR(length=10), nullable=False),
    sa.Column('head', sa.VARCHAR(length=15), nullable=True),
    sa.Column('service_charge', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.VARCHAR(), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.VARCHAR(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('master',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), nullable=False),
    sa.Column('address', sa.VARCHAR(length=40), nullable=False),
    sa.Column('city', sa.VARCHAR(length=20), nullable=False),
    sa.Column('pin', sa.VARCHAR(length=6), nullable=True),
    sa.Column('contact1', sa.VARCHAR(length=10), nullable=True),
    sa.Column('contact2', sa.VARCHAR(length=10), nullable=True),
    sa.Column('gst', sa.VARCHAR(length=15), nullable=True),
    sa.Column('remark', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=20), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_master_code'), 'master', ['code'], unique=False)
    op.create_table('challan',
    sa.Column('challan_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=5), nullable=False),
    sa.Column('challan_date', sa.DATE(), nullable=False),
    sa.Column('desc1', sa.VARCHAR(length=30), nullable=False),
    sa.Column('qty1', sa.INTEGER(), nullable=False),
    sa.Column('unit1', sa.VARCHAR(length=8), nullable=False),
    sa.Column('desc2', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty2', sa.INTEGER(), nullable=True),
    sa.Column('unit2', sa.VARCHAR(length=8), nullable=True),
    sa.Column('desc3', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty3', sa.INTEGER(), nullable=True),
    sa.Column('unit3', sa.VARCHAR(length=8), nullable=True),
    sa.Column('desc4', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty4', sa.INTEGER(), nullable=True),
    sa.Column('unit4', sa.VARCHAR(length=8), nullable=True),
    sa.Column('desc5', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty5', sa.INTEGER(), nullable=True),
    sa.Column('unit5', sa.VARCHAR(length=8), nullable=True),
    sa.Column('desc6', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty6', sa.INTEGER(), nullable=True),
    sa.Column('unit6', sa.VARCHAR(length=8), nullable=True),
    sa.Column('desc7', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty7', sa.INTEGER(), nullable=True),
    sa.Column('unit7', sa.VARCHAR(length=8), nullable=True),
    sa.Column('desc8', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty8', sa.INTEGER(), nullable=True),
    sa.Column('unit8', sa.VARCHAR(length=8), nullable=True),
    sa.Column('order_number', sa.VARCHAR(length=15), nullable=True),
    sa.Column('order_date', sa.DATE(), nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(length=15), nullable=True),
    sa.Column('invoice_date', sa.DATE(), nullable=True),
    sa.Column('remark', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=15), nullable=False),
    sa.ForeignKeyConstraint(['code'], ['master.code'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('challan_number')
    )
    op.create_index(op.f('ix_challan_challan_number'), 'challan', ['challan_number'], unique=False)
    op.create_index(op.f('ix_challan_code'), 'challan', ['code'], unique=False)
    op.create_table('market',
    sa.Column('mcode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=5), nullable=False),
    sa.Column('receive_date', sa.DATE(), nullable=False),
    sa.Column('division', sa.VARCHAR(length=15), nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(length=10), nullable=False),
    sa.Column('invoice_date', sa.DATE(), nullable=False),
    sa.Column('challan_number', sa.VARCHAR(length=10), nullable=True),
    sa.Column('challan_date', sa.DATE(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('delivery_date', sa.DATE(), nullable=True),
    sa.Column('delivery_by', sa.VARCHAR(length=20), nullable=True),
    sa.Column('remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('final_status', sa.CHAR(length=1), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=15), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=15), nullable=True),
    sa.ForeignKeyConstraint(['code'], ['master.code'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('mcode')
    )
    op.create_index(op.f('ix_market_code'), 'market', ['code'], unique=False)
    op.create_index(op.f('ix_market_mcode'), 'market', ['mcode'], unique=False)
    op.create_table('out_of_warranty',
    sa.Column('srf_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('srf_date', sa.DATE(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=5), nullable=False),
    sa.Column('division', sa.VARCHAR(length=15), nullable=False),
    sa.Column('head', sa.VARCHAR(length=20), nullable=True),
    sa.Column('service_charge', sa.INTEGER(), nullable=False),
    sa.Column('service_charge_waive', sa.CHAR(length=1), nullable=False),
    sa.Column('collection_date', sa.DATE(), nullable=True),
    sa.Column('waive_details', sa.VARCHAR(length=40), nullable=True),
    sa.Column('model', sa.VARCHAR(length=30), nullable=False),
    sa.Column('serial_number', sa.VARCHAR(length=15), nullable=False),
    sa.Column('problem', sa.VARCHAR(length=30), nullable=True),
    sa.Column('remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('challan_number', sa.VARCHAR(length=6), nullable=True),
    sa.Column('challan_date', sa.DATE(), nullable=True),
    sa.Column('challan', sa.CHAR(length=1), nullable=False),
    sa.Column('received_by', sa.VARCHAR(length=20), nullable=True),
    sa.Column('estimate_date', sa.DATE(), nullable=True),
    sa.Column('vendor_date1', sa.DATE(), nullable=True),
    sa.Column('vendor_date2', sa.DATE(), nullable=True),
    sa.Column('vendor_cost1', sa.FLOAT(), nullable=True),
    sa.Column('vendor_cost2', sa.FLOAT(), nullable=True),
    sa.Column('vendor_settlement_date', sa.DATE(), nullable=True),
    sa.Column('vendor_settled', sa.VARCHAR(length=1), nullable=False),
    sa.Column('repair_date', sa.DATE(), nullable=True),
    sa.Column('work_done', sa.VARCHAR(length=50), nullable=True),
    sa.Column('rewinding_cost', sa.FLOAT(), nullable=True),
    sa.Column('other_cost', sa.FLOAT(), nullable=True),
    sa.Column('spare1', sa.VARCHAR(length=20), nullable=True),
    sa.Column('cost1', sa.FLOAT(), nullable=True),
    sa.Column('spare2', sa.VARCHAR(length=20), nullable=True),
    sa.Column('cost2', sa.FLOAT(), nullable=True),
    sa.Column('spare3', sa.VARCHAR(length=20), nullable=True),
    sa.Column('cost3', sa.FLOAT(), nullable=True),
    sa.Column('spare4', sa.VARCHAR(length=20), nullable=True),
    sa.Column('cost4', sa.FLOAT(), nullable=True),
    sa.Column('spare5', sa.VARCHAR(length=20), nullable=True),
    sa.Column('cost5', sa.FLOAT(), nullable=True),
    sa.Column('spare6', sa.VARCHAR(length=20), nullable=True),
    sa.Column('cost6', sa.FLOAT(), nullable=True),
    sa.Column('spare_cost', sa.FLOAT(), nullable=True),
    sa.Column('godown_cost', sa.FLOAT(), nullable=True),
    sa.Column('discount', sa.FLOAT(), nullable=True),
    sa.Column('total', sa.FLOAT(), nullable=True),
    sa.Column('gst', sa.CHAR(length=1), nullable=False),
    sa.Column('gst_amount', sa.FLOAT(), nullable=True),
    sa.Column('final_amount', sa.FLOAT(), nullable=True),
    sa.Column('round_off', sa.FLOAT(), nullable=True),
    sa.Column('receive_amount', sa.FLOAT(), nullable=True),
    sa.Column('delivery_date', sa.DATE(), nullable=True),
    sa.Column('pc_number', sa.INTEGER(), nullable=True),
    sa.Column('invoice_number', sa.INTEGER(), nullable=True),
    sa.Column('vendor_bill_number', sa.VARCHAR(length=8), nullable=True),
    sa.Column('final_status', sa.VARCHAR(length=1), nullable=False),
    sa.Column('settlement_date', sa.DATE(), nullable=True),
    sa.Column('final_settled', sa.VARCHAR(length=1), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=15), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=15), nullable=True),
    sa.ForeignKeyConstraint(['code'], ['master.code'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('srf_number')
    )
    op.create_index(op.f('ix_out_of_warranty_code'), 'out_of_warranty', ['code'], unique=False)
    op.create_index(op.f('ix_out_of_warranty_srf_number'), 'out_of_warranty', ['srf_number'], unique=False)
    op.create_table('retail',
    sa.Column('rcode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('retail_date', sa.DATE(), nullable=False),
    sa.Column('division', sa.VARCHAR(length=20), nullable=False),
    sa.Column('code', sa.VARCHAR(length=5), nullable=False),
    sa.Column('details', sa.VARCHAR(length=40), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('received', sa.CHAR(length=1), nullable=False),
    sa.Column('settlement_date', sa.DATE(), nullable=True),
    sa.Column('final_status', sa.CHAR(length=1), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=15), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=15), nullable=True),
    sa.ForeignKeyConstraint(['code'], ['master.code'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('rcode')
    )
    op.create_index(op.f('ix_retail_code'), 'retail', ['code'], unique=False)
    op.create_index(op.f('ix_retail_rcode'), 'retail', ['rcode'], unique=False)
    op.create_table('warranty',
    sa.Column('srf_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=5), nullable=False),
    sa.Column('srf_date', sa.DATE(), nullable=False),
    sa.Column('head', sa.VARCHAR(length=15), nullable=False),
    sa.Column('division', sa.VARCHAR(length=15), nullable=False),
    sa.Column('model', sa.VARCHAR(length=30), nullable=False),
    sa.Column('serial_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('problem', sa.VARCHAR(length=30), nullable=False),
    sa.Column('remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('complaint_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('sticker_number', sa.VARCHAR(length=15), nullable=True),
    sa.Column('asc_name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('challan_number', sa.VARCHAR(length=6), nullable=True),
    sa.Column('challan_date', sa.DATE(), nullable=True),
    sa.Column('challan', sa.CHAR(length=1), nullable=False),
    sa.Column('courier', sa.VARCHAR(length=15), nullable=True),
    sa.Column('receive_date', sa.DATE(), nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(length=16), nullable=True),
    sa.Column('invoice_date', sa.DATE(), nullable=True),
    sa.Column('repair_date', sa.DATE(), nullable=True),
    sa.Column('delivery_date', sa.DATE(), nullable=True),
    sa.Column('delivered_by', sa.VARCHAR(length=20), nullable=True),
    sa.Column('final_status', sa.CHAR(length=1), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=15), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=15), nullable=True),
    sa.ForeignKeyConstraint(['code'], ['master.code'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('srf_number')
    )
    op.create_index(op.f('ix_warranty_code'), 'warranty', ['code'], unique=False)
    op.create_index(op.f('ix_warranty_srf_number'), 'warranty', ['srf_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warranty_srf_number'), table_name='warranty')
    op.drop_index(op.f('ix_warranty_code'), table_name='warranty')
    op.drop_table('warranty')
    op.drop_index(op.f('ix_retail_rcode'), table_name='retail')
    op.drop_index(op.f('ix_retail_code'), table_name='retail')
    op.drop_table('retail')
    op.drop_index(op.f('ix_out_of_warranty_srf_number'), table_name='out_of_warranty')
    op.drop_index(op.f('ix_out_of_warranty_code'), table_name='out_of_warranty')
    op.drop_table('out_of_warranty')
    op.drop_index(op.f('ix_market_mcode'), table_name='market')
    op.drop_index(op.f('ix_market_code'), table_name='market')
    op.drop_table('market')
    op.drop_index(op.f('ix_challan_code'), table_name='challan')
    op.drop_index(op.f('ix_challan_challan_number'), table_name='challan')
    op.drop_table('challan')
    op.drop_index(op.f('ix_master_code'), table_name='master')
    op.drop_table('master')
    op.drop_table('users')
    op.drop_table('service_charge')
    op.drop_table('service_centre')
    op.drop_index(op.f('ix_blockedjti_jti'), table_name='blockedjti')
    op.drop_table('blockedjti')
    # ### end Alembic commands ###
