"""Challan

Revision ID: f7cb7a5b9050
Revises: f97723c12c27
Create Date: 2025-11-08 12:10:48.657995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f7cb7a5b9050'
down_revision: Union[str, Sequence[str], None] = 'f97723c12c27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challan',
    sa.Column('challan_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=5), nullable=False),
    sa.Column('challan_date', sa.DATE(), nullable=False),
    sa.Column('desc1', sa.VARCHAR(length=30), nullable=False),
    sa.Column('qty1', sa.INTEGER(), nullable=False),
    sa.Column('unit1', sa.VARCHAR(length=8), nullable=False),
    sa.Column('desc2', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty2', sa.INTEGER(), nullable=True),
    sa.Column('unit2', sa.VARCHAR(length=8), nullable=True),
    sa.Column('desc3', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty3', sa.INTEGER(), nullable=True),
    sa.Column('unit3', sa.VARCHAR(length=8), nullable=True),
    sa.Column('desc4', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty4', sa.INTEGER(), nullable=True),
    sa.Column('unit4', sa.VARCHAR(length=8), nullable=True),
    sa.Column('desc5', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty5', sa.INTEGER(), nullable=True),
    sa.Column('unit5', sa.VARCHAR(length=8), nullable=True),
    sa.Column('desc6', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty6', sa.INTEGER(), nullable=True),
    sa.Column('unit6', sa.VARCHAR(length=8), nullable=True),
    sa.Column('desc7', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty7', sa.INTEGER(), nullable=True),
    sa.Column('unit7', sa.VARCHAR(length=8), nullable=True),
    sa.Column('desc8', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty8', sa.INTEGER(), nullable=True),
    sa.Column('unit8', sa.VARCHAR(length=8), nullable=True),
    sa.Column('order_number', sa.VARCHAR(length=15), nullable=True),
    sa.Column('order_date', sa.DATE(), nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(length=15), nullable=True),
    sa.Column('invoice_date', sa.DATE(), nullable=True),
    sa.Column('remark', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=15), nullable=False),
    sa.ForeignKeyConstraint(['code'], ['master.code'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('challan_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('challan')
    # ### end Alembic commands ###
