"""Initial Migration

Revision ID: f97723c12c27
Revises: 16ef08de4db0
Create Date: 2025-11-08 11:23:17.790061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f97723c12c27'
down_revision: Union[str, Sequence[str], None] = '16ef08de4db0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ow_service_charge',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('division', sa.VARCHAR(length=10), nullable=False),
    sa.Column('head', sa.VARCHAR(length=15), nullable=False),
    sa.Column('service_charge', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_centre',
    sa.Column('asc_name', sa.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('asc_name')
    )
    op.create_table('market',
    sa.Column('mcode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=5), nullable=False),
    sa.Column('receive_date', sa.DATE(), nullable=False),
    sa.Column('division', sa.VARCHAR(length=15), nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(length=10), nullable=False),
    sa.Column('invoice_date', sa.DATE(), nullable=False),
    sa.Column('challan_number', sa.VARCHAR(length=10), nullable=True),
    sa.Column('challan_date', sa.DATE(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('delivery_date', sa.DATE(), nullable=True),
    sa.Column('delivery_by', sa.VARCHAR(length=20), nullable=True),
    sa.Column('remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('final_status', sa.CHAR(length=1), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=15), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=15), nullable=True),
    sa.ForeignKeyConstraint(['code'], ['master.code'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('mcode')
    )
    op.create_table('retail',
    sa.Column('rcode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rdate', sa.DATE(), nullable=False),
    sa.Column('division', sa.VARCHAR(length=20), nullable=False),
    sa.Column('code', sa.VARCHAR(length=5), nullable=False),
    sa.Column('details', sa.VARCHAR(length=40), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('received', sa.CHAR(length=1), nullable=False),
    sa.Column('settlement_date', sa.DATE(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=15), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=15), nullable=True),
    sa.ForeignKeyConstraint(['code'], ['master.code'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('rcode')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retail')
    op.drop_table('market')
    op.drop_table('service_centre')
    op.drop_table('ow_service_charge')
    # ### end Alembic commands ###
